### ISSUE TITLE
I can read your npm password...

### ISSUE THREAD

**Issue by simbo** [tlei123/generator-tze#2]
[See my comment at stackoverflow](http://stackoverflow.com/questions/27467861/no-api-key-after-npm-login-for-travis/27588815#comments-28933299)...

**Comment by tlei123** [comment]
Changed NPM acct pw, re-generated and travis-encrypted NPM API key.

Bumped and pre-released on GitHub, and verified successful Travis auto-build-n-deploy to NPMJS.org.  NPMJS.org now shows v0.0.11, released 3 min. ago.

**Comment by tlei123** [comment]
THX, simbo, for the heads-up!  I would've totally missed the travis-encrypt step w/o you.

Travis-CLI gem installed successfully tonight, so I could follow your answer to do this fix.  I deleted my answer already so no one else would make the same boo-boo.  :D
